<?php
use \backend\models\StmtMonitoring;

$model = new StmtMonitoring();

$total = StmtMonitoring::getTotal();                // Общее количество
$statement = StmtMonitoring::getTotal(3);           // Заявления
$consultation = StmtMonitoring::getTotal(2);        // Консультации
$plaint = StmtMonitoring::getTotal(1);              // Жалобы
$proposition = StmtMonitoring::getTotal(4);         // Предложения
$tfoms = StmtMonitoring::getTotal(null, 1);         // ТФОМС
$insurance = StmtMonitoring::getTotal(null, 0);     // Страховые

$voice_stmt = StmtMonitoring::getVoiceStmt(0);          //Устные обращения
$write_stmt = StmtMonitoring::getVoiceStmt(1);          //Письменные обращения
$hot_line_stmt = StmtMonitoring::getVoiceStmt(0, 2);    //горячая линия 8-800
$web_stmt = StmtMonitoring::getVoiceStmt(1, 9);         //по сети «Интернет»

$range = Yii::$app->request->post('Monitoring')['range']?Yii::$app->request->post('Monitoring')['range']:Yii::$app->request->post('range');

$text = '
<p style="margin-bottom: .0001pt; text-align: center; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Информация о работе Контакт &ndash; центра ТФОМС СК с обращениями граждан&nbsp; за <span style="text-decoration: underline;"> '. $range .' </span> период </span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Количество обращений, поступивших в территориальный фонд обязательного медицинского страхования Ставропольского края и страховые медицинские организации составило '. $total .'&nbsp;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Территориальным фондом обязательного медицинского страхования Ставропольского края и страховыми медицинскими организациями:</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">принято '. $statement .' заявлений;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">проведено '. $consultation .' консультаций по вопросам обязательного медицинского страхования;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">рассмотрено '. $plaint .'&nbsp; жалоб;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">получено '. $proposition .'&nbsp; предложений по вопросам организации обязательного медицинского страхования и здравоохранения.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Из общего количества обращений поступило:</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">в страховые медицинские организации - '. $insurance .' обращений или '. number_format($insurance/$total*100, 2, '.', '') .'% от общего количества обращений;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">в территориальный фонд обязательного медицинского страхования Ставропольского края - '. $tfoms .' обращений или '. number_format($tfoms/$total*100, 2, '.', '') .'% .</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Устные обращения составили '. $voice_stmt .' или '. number_format($voice_stmt/$total*100, 2, '.', '') .'% от общего количества обращений, из них на &laquo;горячую линию&raquo; поступило '. $hot_line_stmt .' обращений или '. StmtMonitoring::precent($hot_line_stmt, $voice_stmt) .'% от общего количества устных обращений.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Письменные обращения составили '. $write_stmt .' или '. number_format($write_stmt/$total*100, 2, '.', '') .'% от общего количества обращений, из них по сети &laquo;Интернет&raquo; поступило '. $web_stmt .' обращений, что составляет '. StmtMonitoring::precent($web_stmt, $write_stmt) .'% от общего количества письменных обращений.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Причины обращений граждан в Контакт-центр за консультациями:</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">об обеспечении полисами ОМС - '. StmtMonitoring::getCauseStmt('к 4.1', 2) .' консультаций или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.1', 2), $consultation) .'% от общего количества обращений за консультациями, в том числе об обеспечении полисами ОМС иностранных граждан, беженцев '. StmtMonitoring::getCauseStmt('к 4.1.1', 2) .';</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о выборе медицинской организации в сфере обязательного медицинского страхования - '. StmtMonitoring::getCauseStmt('к 4.2', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.2', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о выборе врача - '. StmtMonitoring::getCauseStmt('к 4.3', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.3', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о выборе или замене страховой медицинской организации - '. StmtMonitoring::getCauseStmt('к 4.4', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.4', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">об организации работы медицинской организации - '. StmtMonitoring::getCauseStmt('к 4.5', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.5', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о санитарно-гигиеническом состоянии медицинской организации - '. StmtMonitoring::getCauseStmt('к 4.6', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.6', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">об этике и деонтологии медицинских работников - '. StmtMonitoring::getCauseStmt('к 4.7', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.7', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
о качестве медицинской помощи - '. StmtMonitoring::getCauseStmt('к 4.8', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.8', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о лекарственном обеспечении при оказании медицинской помощи - '. StmtMonitoring::getCauseStmt('к 4.9', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.9', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">об отказе в оказании медицинской помощи по программам ОМС - '. StmtMonitoring::getCauseStmt('к 4.10', 2) .'  или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.10', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о получении медицинской помощи по базовой программе ОМС вне территории страхования - '. StmtMonitoring::getCauseStmt('к 4.11', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.11', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">о взимании денежных средств за медицинскую помощь по программам ОМС - '. StmtMonitoring::getCauseStmt('к 4.12', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.12', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
о видах, качестве и условиях предоставления медицинской помощи по программам ОМС - '. StmtMonitoring::getCauseStmt('к 4.12.1', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.12.1', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
о платных медицинских услугах, оказываемых в медицинских организациях - '. StmtMonitoring::getCauseStmt('к 4.13', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.13', 2), $consultation) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
консультации по другим причинам - '. StmtMonitoring::getCauseStmt('к 4.14', 2) .' или '. StmtMonitoring::precent(StmtMonitoring::getCauseStmt('к 4.14', 2), $consultation) .'%. К консультациям по &laquo;другим&raquo; причинам отнесены обращения по выдаче справок о стоимости и объеме оказанной медицинской помощи, а также по вопросам, не относящимся к сфере 
ОМС (возможности получения квоты на высокотехнологичное лечение в клиниках федерального уровня, льготного лекарственного обеспечения льготных категорий граждан, нарушения при выдаче листа нетрудоспособности, порядок получения путевки на санаторно-курортное лечение и др.).</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
По поводу нарушения прав и законных интересов застрахованных лиц в территориальный фонд обязательного медицинского страхования Ставропольского края и в страховые медицинские организации поступило '. $plaint .' жалоб.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Жалобы поступили:</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">в территориальный фонд обязательного медицинского страхования Ставропольского края - '. StmtMonitoring::getTotal(1, 1) .' или '. StmtMonitoring::precent(StmtMonitoring::getTotal(1, 1), $plaint) .'% от общего количества жалоб;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">в страховые медицинские организации - '. StmtMonitoring::getTotal(1, 0) .' или '. StmtMonitoring::precent(StmtMonitoring::getTotal(1, 0), $plaint) .'% от общего количества жалоб.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Обоснованными признаны '. StmtMonitoring::getPlaint() .' жалоб или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(), $plaint) .'% от общего количества жалоб.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">Причины обоснованных жалоб, поступивших за&nbsp; <span style="text-decoration: underline;">('. $range .'):</span></span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">обеспечение полисами ОМС - '. StmtMonitoring::getPlaint(['ж 3']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 3']), StmtMonitoring::getPlaint()) .'% от общего количества обоснованных жалоб;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
выбор медицинской организации в сфере ОМС - '. StmtMonitoring::getPlaint(['ж 4.1', 'ж 4.2']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 4.1', 'ж 4.2']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
выбор врача - '. StmtMonitoring::getPlaint(['ж 5']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 5']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
выбор или замена СМО - '. StmtMonitoring::getPlaint(['ж 6.1', 'ж 6.2', 'ж 6.3']) .'&nbsp;или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 6.1', 'ж 6.2', 'ж 6.3']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
организация работы медицинской организации - '. StmtMonitoring::getPlaint(['ж 7']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 7']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
санитарно-гигиеническое состояние медицинской организации - '. StmtMonitoring::getPlaint(['ж 8']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 8']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
материально-техническое обеспечение медицинской организации - '. StmtMonitoring::getPlaint(['ж 9']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 9']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
этика и деонтология медицинских работников - '. StmtMonitoring::getPlaint(['ж 10']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 10']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
о качестве медицинской помощи - '. StmtMonitoring::getPlaint(['ж 11']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 11']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
лекарственное обеспечение при оказании медицинской помощи - '. StmtMonitoring::getPlaint(['ж 12']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 12']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
отказ в медицинской помощи по программам ОМС - '. StmtMonitoring::getPlaint(['ж 13.1', 'ж 13.2']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 13.1', 'ж 13.2']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
неисполнение страховой медицинской организацией обязанностей по договору - '. StmtMonitoring::getPlaint(['ж 14']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 14']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
взимание денежных средств за медицинскую помощь по программам ОМС - '. StmtMonitoring::getPlaint(['ж 15.1', 'ж 15.2']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 15.1', 'ж 15.2']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
неправомерное распространение персональных данных - '. StmtMonitoring::getPlaint(['ж 16']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 16']), StmtMonitoring::getPlaint()) .'%;</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">
прочие причины - '. StmtMonitoring::getPlaint(['ж 17']) .' или '. StmtMonitoring::precent(StmtMonitoring::getPlaint(['ж 17']), StmtMonitoring::getPlaint()) .'%. Обоснованные жалобы по &laquo;прочим&raquo; причинам в основном связаны с обращениями застрахованных лиц посредством &laquo;Личного кабинета&raquo; на сайт ТФОМС СК о том, что медицинские услуги, оплаченные за счет средств ОМС, фактически не оказывались.</span></p>
<p style="margin-bottom: .0001pt; text-align: justify; text-indent: 35.45pt; line-height: normal;"><span style="font-size: 14.0pt; font-family: &quot;Times New Roman&quot;,serif;">По всем письменным жалобам проведен контроль условий и качества оказания медицинской помощи. При доказанности допущенных медицинскими организациями нарушений результаты рассмотрения обращений доведены до сведения администраций медицинских организаций с требованиями проведения служебного разбора по установленным фактам нарушений и рекомендациями проведения конкретных мероприятий по устранению выявленных недостатков. По результатам рассмотрения обращений, связанных с взиманием денежных средств за медицинскую помощь по программам ОМС, при доказанности допущенных нарушений, медицинские организации осуществили возмещение денежных средств. Результаты рассмотрения всех обращений доведены до сведения заявителей.</span></p>
';

echo $text;